name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Deploy to EC2
        env:
          EC2_HOST: 13.40.3.183
          EC2_USER: ubuntu
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Copy project files to EC2 instance
          scp -o StrictHostKeyChecking=no -i private_key.pem -r . $EC2_USER@$EC2_HOST:/home/ubuntu/GeoMart-Frontend

          # Connect to EC2 and restart the frontend application
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/GeoMart-Frontend
            npm install
            npm run build
            pm2 restart all || pm2 start npm --name "geomart-frontend" -- start
          EOF

          # Remove the private key for security
          rm -f private_key.pem
